### ISSUE TITLE
More configuration options

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/doc-diff#3]
The configuration options haven't settled yet, I'm still playing around with implementation at the pull request builder. I think the existing options are maybe sufficient, but the READTHEDOCS_DATA needs some more context data to make this extension possible.

Namely, the context data needs to include the full URL from the resolver for the base page to do the DOM comparison request against. For many projects, this would look like: "https://test-builds.readthedocs.io/en/latest"

With this piece, I'm not sure we need granular control over version/langauge/etc.

**Comment by humitos** [comment]
If it's easy to include the full URL from the resolver into `READTHEDOCS_DATA`, I'd go that way so no configuration is required for this extension 💯

**Comment by agjohnson** [comment]
:+1: I suppose this would be a good issue to throw on the application issue tracker.

https://github.com/readthedocs/readthedocs.org/issues/9532

**Comment by stsewd** [comment]
> With this piece, I'm not sure we need granular control over version/langauge/etc.

I also think we shouldn't expose separate options for language/version, and just have one setting `base_url`.

**Comment by humitos** [comment]
We are not using `READTHEDOCS_DATA` anymore. If anything, the data has to be added the new API endpoint. See https://github.com/readthedocs/readthedocs.org/issues/9532
